#!/bin/sh
# Resolve all frontend dependencies that the application requires to develop.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

export YARN_ENABLE_IMMUTABLE_INSTALLS=false
rm -f yarn.lock
node ./script/merge_requirements.js
yarn install
