#!/bin/sh
# Builds the frontend for production

# Stop on errors
set -e

cd "$(dirname "$0")/.."

if [ ! -d "./node_modules" ]; then
    echo "Directory /node_modules DOES NOT exists."
    echo "Running yarn install"
    yarn install
fi

./node_modules/.bin/gulp -f homeassistant-frontend/gulpfile.js gen-icons-json
./node_modules/.bin/gulp build
